---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "k8s-log-catcher.fullname" . }}
  labels:
    {{- include "k8s-log-catcher.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "k8s-log-catcher.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "k8s-log-catcher.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ include "k8s-log-catcher.image" . }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - "bin/bash"
              - "-c"
              - for pod in $(kubectl -n {{ .Values.config.namespace }} get pods {{ if .Values.config.labels }}-l {{ join "," .Values.config.labels }}{{ end }} -o custom-columns=:metadata.name); do bash -c "kubectl -n {{ .Values.config.namespace }} logs  $pod  --since-time=`date -d @$(($(date +%s) - {{ .Values.config.logCaptureSeconds }})) +%Y-%m-%dT%H:%M:%SZ` > {{ .Values.config.logPath}}/{{ .Values.config.logFilePrefix }}`date +%Y-%m-%dT%H:%M:%SZ`-$pod.log"; done
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
              {{- if .Values.persistence.enabled }}
              - name: data
                mountPath: /data
              {{- end }}
              {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 14 }}
              {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          volumes:
            {{- if .Values.persistence.enabled }}
            - name: data
              persistentVolumeClaim:
                claimName: {{ template "k8s-log-catcher.fullname" . }}
            {{- end }}
            {{- if .Values.extraVolumes }}
            {{- toYaml .Values.extraVolumes | nindent 12 }}
            {{- end }}
