{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "k8s-log-catcher.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "k8s-log-catcher.name" . }}
    app.kubernetes.io/name: {{ include "k8s-log-catcher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "controller"
    helm.sh/chart: {{ include "k8s-log-catcher.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  - pods/log
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "k8s-log-catcher.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "k8s-log-catcher.name" . }}
    app.kubernetes.io/name: {{ include "k8s-log-catcher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "controller"
    helm.sh/chart: {{ include "k8s-log-catcher.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "k8s-log-catcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-log-catcher.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}

